FROM node:10-slim

RUN mkdir -p /usr/src/app && chown -R node:node /usr/src/app

WORKDIR /usr/src/app

USER node

RUN yarn global add sequelize-cli

COPY --chown=node:node package.json yarn.lock ./

RUN yarn

COPY --chown=node:node . .
